//Contract based on https://docs.openzeppelin.com/contracts/3.x/erc721
// SPDX-License-Identifier: MIT
pragma solidity 0.7.0;

import "OpenZeppelin/openzeppelin-contracts@3.1.0-solc-0.7/contracts/token/ERC721/ERC721.sol";
import "OpenZeppelin/openzeppelin-contracts@3.1.0-solc-0.7/contracts/utils/Counters.sol";
import "OpenZeppelin/openzeppelin-contracts@3.1.0-solc-0.7/contracts//access/Ownable.sol";


contract Chess_Byte is ERC721, Ownable {

    using Counters for Counters.Counter;
    Counters.Counter private _tokenIds;

    address public minter;
    uint256 public cprice;
    uint256 private pending_withdrawals;
    bool public state;
    mapping(uint256 => bool) usedIds;

    // event Rhash(bytes32 value);
   
    constructor() ERC721("ChessByte", "CHY") {
        minter = msg.sender;
        cprice = 6100000000000000; // ~20 usd
        state = true;
    }

    function mint(string memory tokenURI)
        private 
        returns (uint256)
    {
        // If you are sending to a wrong address
        // you will loose money for a gas fee and nothing
        // we can do about it, so becarefull with your adress
        _tokenIds.increment();

        uint256 newItemId = _tokenIds.current();
        _mint(minter, newItemId);
        _setTokenURI(newItemId, tokenURI);

        return newItemId;
    }

    function buy_token(uint256 tokenID, string memory token, string memory tokenURI,
                        bytes32 hash, uint8 v, bytes32 r, bytes32 s) 
                        payable public
        {
        require(state);

        // Make sure msg is generated by minter
        // bytes32 message = prefixed(keccak256(tokenURI));
        bytes32 excpected_hash = keccak256(abi.encodePacked(tokenID, token, tokenURI, msg.sender, address(this))); 
        bytes32 _hash = keccak256(abi.encodePacked("\x19Ethereum Signed Message:\n32", excpected_hash));

        require(hash == _hash);
        require(ecrecover(_hash, v, r, s) == minter, "NFT not authorized by this contract");

        // Check id
        require(!usedIds[tokenID], "Token has wrong ID");
       
        // Check ether sent
        require(msg.value >= cprice, "Insufficient funds to buy");

        // Create token first
        uint256 mint_id = mint(tokenURI); 
        usedIds[tokenID] = true;       
        // transfer the token to the buyer
        _transfer(minter, msg.sender, mint_id);
    }

    function update_price(uint256 new_price) onlyOwner public {
        cprice = new_price;
    }

    function token_size() onlyOwner public returns(uint256){
        return _tokenIds.current();
    }

    function withdraw() onlyOwner public {

        require(address(this).balance > 0);
        address payable receiver = payable(minter);

        uint256 amount = address(this).balance;
        receiver.transfer(amount);
    }

    function stop() onlyOwner public{
        state = false;
    }
    function resume() onlyOwner public{
        state = true;
    }

    function destruct() onlyOwner public{}
}